heaven-frontend:
  ports:
  - 80:80/tcp
  - 443:443/tcp
  environment:
    CONTAINER_DNS_TEMPLATE: ${CONTAINER_DNS_TEMPLATE}
    DNS_RESOLVER: 169.254.169.250
    ADDITIONAL_CONFIG: ${ADDITIONAL_CONFIG}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: heaven=1
  tty: true
  image: extremeprog/heaven
  stdin_open: true

